/**:
  ros__parameters:
    robot_description_kinematics:
      ur_with_gripper:
        kinematics_solver: kdl_kinematics_plugin/KDLKinematicsPlugin
        kinematics_solver_search_resolution: 0.005
        kinematics_solver_timeout: 0.01
        kinematics_solver_attempts: 3
        
        /**:
  ros__parameters:
    robot_description_kinematics:
      ur_with_gripper:
        kinematics_solver: trac_ik_kinematics_plugin/TRAC_IKKinematicsPlugin
        kinematics_solver_timeout: 0.1
        solve_type: Speed
        episilon: 1e-5
