planning_plugins:
  - stomp_moveit/StompPlanner

# The order of the elements in the adapter corresponds to the order they are processed by the motion planning pipeline.

ur_with_gripper:
  num_timesteps: 60
  num_iterations: 40
  num_iterations_after_valid: 0
  num_rollouts: 30
  max_rollouts: 30
  exponentiated_cost_sensitivity: 0.5
  control_cost_weight: 0.1
  delta_t: 0.1

